-- DDL Schema for Faculty Activity Management Portal

-- 1. Master Data Tables
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS designations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

-- 2. User Accounts Table
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    employee_id TEXT UNIQUE NOT NULL,
    department TEXT NOT NULL,
    designation TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('lecturer', 'admin')) DEFAULT 'lecturer',
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
    reset_password_token TEXT,
    reset_password_expires TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Activity Submissions Table
CREATE TABLE IF NOT EXISTS submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    academic_year TEXT NOT NULL,
    file_path TEXT NOT NULL,
    detail_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL CHECK (status IN ('pending', 'verified', 'rejected')) DEFAULT 'pending',
    submitted_at TIMESTAMPTZ DEFAULT now()
);

-- 4. User Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Audit logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    target TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT now()
);

-- 6. Pre-seed Default Master Lists
INSERT INTO departments (name) VALUES
('Computer Science & Engineering'),
('Information Science & Engineering'),
('Electronics & Communication Engineering'),
('Mechanical Engineering'),
('Civil Engineering'),
('Basic Sciences & Humanities')
ON CONFLICT (name) DO NOTHING;

INSERT INTO designations (name) VALUES
('Principal'),
('Professor & HOD'),
('Professor'),
('Associate Professor'),
('Assistant Professor'),
('Senior Lecturer'),
('Lecturer')
ON CONFLICT (name) DO NOTHING;

INSERT INTO categories (name) VALUES
('Research Paper'),
('Research Conducted'),
('FDP Attended'),
('FDP Conducted'),
('Other')
ON CONFLICT (name) DO NOTHING;
